# Snapshot generated with gclient revinfo --snapshot
solutions = [
  { "name"        : "trunk",
    "url"         : "https://github.com/lukeweber/webrtc-jingle-client.git",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {
      "scons": None,
      "trunk/base": 'https://github.com/lukeweber/chromium-trunk-base-override.git@455807ec9e2280234ceac98b817ec4f160860724',
      "trunk/build": 'https://github.com/lukeweber/chromium-trunk-build-override.git@f02288898c2a5e0e59026a426efaef4080014e87',
      "trunk/testing": 'http://src.chromium.org/svn/trunk/src/testing@182149',
      "trunk/testing/gmock": 'http://googlemock.googlecode.com/svn/trunk@405',
      "trunk/third_party/ashmem": 'http://src.chromium.org/svn/trunk/src/third_party/ashmem@182149',
      "trunk/third_party/chromium_deps": None,
      "trunk/third_party/expat": 'http://src.chromium.org/svn/trunk/src/third_party/expat@182149',
      "trunk/third_party/google-gflags/src": 'http://google-gflags.googlecode.com/svn/trunk/src@45',
      "trunk/third_party/gtest": 'https://github.com/lukeweber/googletest.git@dedaf70c2781f4bee042e7f1d3212f096d55e45f',
      "trunk/third_party/icu": 'http://git.chromium.org/chromium/deps/icu46.git@53ac6db57d9d09e43079f54feec59b735ed23670',
      "trunk/third_party/libevent": 'http://src.chromium.org/svn/trunk/src/third_party/libevent@182149',
      "trunk/third_party/libjingle": 'https://github.com/lukeweber/libjingle-override.git@fd2d93b99797c9e11d6e49475186bb470bb5656f',
      "trunk/third_party/libjingle/build": None,
      "trunk/third_party/libjingle/google_apis/build": None,
      "trunk/third_party/libjingle/net/third_party/nss": None,
      "trunk/third_party/libjingle/third_party/expat": None,
      "trunk/third_party/libjingle/third_party/gtest": None,
      "trunk/third_party/libjingle/third_party/icu": None,
      "trunk/third_party/libjingle/third_party/jsoncpp": None,
      "trunk/third_party/libjingle/third_party/jsoncpp/source": None,
      "trunk/third_party/libjingle/third_party/junit": None,
      "trunk/third_party/libjingle/third_party/libjpeg": None,
      "trunk/third_party/libjingle/third_party/libjpeg_turbo": None,
      "trunk/third_party/libjingle/third_party/libsrtp": None,
      "trunk/third_party/libjingle/third_party/libvpx": None,
      "trunk/third_party/libjingle/third_party/libyuv": None,
      "trunk/third_party/libjingle/third_party/nss": None,
      "trunk/third_party/libjingle/third_party/opus": None,
      "trunk/third_party/libjingle/third_party/opus/src": None,
      "trunk/third_party/libjingle/third_party/protobuf": None,
      "trunk/third_party/libjingle/third_party/sqlite": None,
      "trunk/third_party/libjingle/third_party/webrtc": None,
      "trunk/third_party/libjingle/third_party/yasm": None,
      "trunk/third_party/libjingle/third_party/yasm/source/patched-yasm": None,
      "trunk/third_party/libjingle/third_party/zlib": None,
      "trunk/third_party/libjingle/tools/clang": None,
      "trunk/third_party/libjingle/tools/gyp": None,
      "trunk/third_party/libjingle/tools/protoc_wrapper": None,
      "trunk/third_party/libjingle/tools/python": None,
      "trunk/third_party/libjingle/tools/valgrind": None,
      "trunk/third_party/libjingle/tools/win/supalink": None,
      "trunk/third_party/libjpeg": 'http://src.chromium.org/svn/trunk/src/third_party/libjpeg@182149',
      "trunk/third_party/libjpeg_turbo": 'http://git.chromium.org/chromium/deps/libjpeg_turbo.git@82ce8a6d4ebe12a177c0c3597192f2b4f09e81c3',
      "trunk/third_party/libsrtp/source": 'http://git.chromium.org/chromium/deps/libsrtp.git@362c71e8d0dc205a4ad9f4709d42c25864ac872a',
      "trunk/third_party/libvpx/source/libvpx": 'http://git.chromium.org/webm/libvpx.git@7a09f6b8926835fc7a8fb59cdf632b2703a640b5',
      "trunk/third_party/libyuv": 'http://git.chromium.org/external/libyuv.git@a9c9242a557c0202454733bab66521bff2e35fc9',
      "trunk/third_party/libyuv/build": None,
      "trunk/third_party/libyuv/google_apis/build": None,
      "trunk/third_party/libyuv/testing": None,
      "trunk/third_party/libyuv/testing/gtest": None,
      "trunk/third_party/libyuv/third_party/libjpeg_turbo": None,
      "trunk/third_party/libyuv/third_party/yasm": None,
      "trunk/third_party/libyuv/third_party/yasm/source/patched-yasm": None,
      "trunk/third_party/libyuv/tools/clang": None,
      "trunk/third_party/libyuv/tools/gyp": None,
      "trunk/third_party/libyuv/tools/python": None,
      "trunk/third_party/libyuv/tools/valgrind": None,
      "trunk/third_party/libyuv/tools/win/supalink": None,
      "trunk/third_party/mach_override": 'http://src.chromium.org/svn/trunk/src/third_party/mach_override@182149',
      "trunk/third_party/modp_b64": 'http://src.chromium.org/svn/trunk/src/third_party/modp_b64@182149',
      "trunk/third_party/openssl": 'https://github.com/lukeweber/openssl-override.git@5c217287aa644aed7ad49e6e1c95926768e6110d',
      "trunk/third_party/opus/": 'http://src.chromium.org/svn/trunk/src/third_party/opus@185324',
      "trunk/third_party/protobuf": 'http://src.chromium.org/svn/trunk/src/third_party/protobuf@182149',
      "trunk/third_party/webrtc": 'https://github.com/lukeweber/webrtc-src-override.git@a0b1421a6b54b6f9ec00e3da279d3be3df804c77',
      "trunk/third_party/yasm": 'http://src.chromium.org/svn/trunk/src/third_party/yasm@182149',
      "trunk/third_party/yasm/source/patched-yasm": 'http://git.chromium.org/chromium/deps/yasm/patched-yasm.git@f164a228f51c17ffc3ed69516a7dc6abdf2d2c8e',
      "trunk/tools/clang": 'http://src.chromium.org/svn/trunk/src/tools/clang@182149',
      "trunk/tools/gyp": 'https://github.com/lukeweber/gyp-override.git@fac7cdecbd2e6e035ead2c4af630722100b92f01',
      "trunk/tools/python": 'http://src.chromium.org/svn/trunk/src/tools/python@182149',
      "trunk/tools/valgrind": 'http://src.chromium.org/svn/trunk/src/tools/valgrind@182149',
      "trunk/tools/win/supalink": 'http://src.chromium.org/svn/trunk/src/tools/win/supalink@182149',
    },
    "safesync_url": "",
  },
]
