LIBJINGLE_CPPFLAGS := \
	-DGTEST_RELATIVE_PATH \
	-DDISABLE_DYNAMIC_CAST \
	-D_REENTRANT \
	-DPOSIX \
	-DOS_LINUX=OS_LINUX \
	-DLINUX \
	-DANDROID \
	-DEXPAT_RELATIVE_PATH \
	-DSRTP_RELATIVE_PATH \
	-DXML_STATIC \
	-DFEATURE_ENABLE_SSL \
	-DHAVE_OPENSSL_SSL_H=1 \
	-DFEATURE_ENABLE_VOICEMAIL \
	-DFEATURE_ENABLE_PSTN \
	-DHAVE_SRTP \
	-DNO_SOUND_SYSTEM \
	-DWEBRTC_RELATIVE_PATH \
	-DEXPAT_RELATIVE_PATH \
	-DHAVE_WEBRTC_VOICE \

MY_LIBJINGLE_C_INCLUDES := \
	$(MY_THIRD_PARTY_PATH)/openssl/openssl/include \
	$(MY_THIRD_PARTY_PATH)/openssl/config/android \
	$(MY_THIRD_PARTY_PATH)/libsrtp/source/config \
	$(MY_THIRD_PARTY_PATH)/libsrtp/source/srtp \
	$(MY_THIRD_PARTY_PATH)/libsrtp/source/srtp/include \
	$(MY_THIRD_PARTY_PATH)/libsrtp/source/srtp/crypto/include \
	$(MY_THIRD_PARTY_PATH) \
	$(MY_THIRD_PARTY_PATH)/libjingle \
	$(MY_THIRD_PARTY_PATH)/webrtc \
	$(MY_THIRD_PARTY_PATH)/webrtc/modules/interface \
	$(MY_THIRD_PARTY_PATH)/expat/files/lib

MY_UNITTEST_CFLAGS :=  $(LIBJINGLE_CPPFLAGS) \
	-DHAVE_STDLIB_H \
	-DHAVE_STRING_H \
	-DCPU_RISC \
	-DSIZEOF_UNSIGNED_LONG=4 \
	-DSIZEOF_UNSIGNED_LONG_LONG=8 \
	-DHAVE_STDINT_H \
	-DHAVE_INTTYPES_H \
	-DHAVE_NETINET_IN_H \
	-DHAVE_UINT64_T \
	-DHAVE_UINT32_T \
	-DHAVE_UINT16_T \
	-DHAVE_UINT8_T \
	-DHAVE_UINT_T \
	-DUSE_WEBRTC_313_BRANCH

GTEST_C_INCLUDES := \
	$(MY_GTEST_PATH) \
	$(MY_GTEST_PATH)/include
