/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tuenti_voice_VoiceClient */

#ifndef _Included_com_tuenti_voice_VoiceClient
#define _Included_com_tuenti_voice_VoiceClient
#ifdef __cplusplus
extern "C" {
#endif
#undef com_tuenti_voice_VoiceClient_CALL_ANSWERED
#define com_tuenti_voice_VoiceClient_CALL_ANSWERED 1L
#undef com_tuenti_voice_VoiceClient_CALL_CALLING
#define com_tuenti_voice_VoiceClient_CALL_CALLING 0L
#undef com_tuenti_voice_VoiceClient_CALL_INCOMING
#define com_tuenti_voice_VoiceClient_CALL_INCOMING 5L
#undef com_tuenti_voice_VoiceClient_CALL_INPROGRESS
#define com_tuenti_voice_VoiceClient_CALL_INPROGRESS 3L
#undef com_tuenti_voice_VoiceClient_CALL_RECIVEDTERMINATE
#define com_tuenti_voice_VoiceClient_CALL_RECIVEDTERMINATE 4L
#undef com_tuenti_voice_VoiceClient_CALL_REJECTED
#define com_tuenti_voice_VoiceClient_CALL_REJECTED 2L
#undef com_tuenti_voice_VoiceClient_CALL_STATE_EVENT
#define com_tuenti_voice_VoiceClient_CALL_STATE_EVENT 0L
#undef com_tuenti_voice_VoiceClient_XMPP_ENGINE_CLOSED
#define com_tuenti_voice_VoiceClient_XMPP_ENGINE_CLOSED 0L
#undef com_tuenti_voice_VoiceClient_XMPP_ENGINE_EVENT
#define com_tuenti_voice_VoiceClient_XMPP_ENGINE_EVENT 1L
#undef com_tuenti_voice_VoiceClient_XMPP_ENGINE_OPEN
#define com_tuenti_voice_VoiceClient_XMPP_ENGINE_OPEN 1L
#undef com_tuenti_voice_VoiceClient_XMPP_ENGINE_OPENING
#define com_tuenti_voice_VoiceClient_XMPP_ENGINE_OPENING 2L
#undef com_tuenti_voice_VoiceClient_XMPP_ENGINE_START
#define com_tuenti_voice_VoiceClient_XMPP_ENGINE_START 3L
#undef com_tuenti_voice_VoiceClient_XMPP_ERROR_AUTH
#define com_tuenti_voice_VoiceClient_XMPP_ERROR_AUTH 6L
#undef com_tuenti_voice_VoiceClient_XMPP_ERROR_BIND
#define com_tuenti_voice_VoiceClient_XMPP_ERROR_BIND 7L
#undef com_tuenti_voice_VoiceClient_XMPP_ERROR_CONN_CLOSED
#define com_tuenti_voice_VoiceClient_XMPP_ERROR_CONN_CLOSED 8L
#undef com_tuenti_voice_VoiceClient_XMPP_ERROR_DOC_CLOSED
#define com_tuenti_voice_VoiceClient_XMPP_ERROR_DOC_CLOSED 9L
#undef com_tuenti_voice_VoiceClient_XMPP_ERROR_EVENT
#define com_tuenti_voice_VoiceClient_XMPP_ERROR_EVENT 2L
#undef com_tuenti_voice_VoiceClient_XMPP_ERROR_NONE
#define com_tuenti_voice_VoiceClient_XMPP_ERROR_NONE 0L
#undef com_tuenti_voice_VoiceClient_XMPP_ERROR_SOCK_ERR
#define com_tuenti_voice_VoiceClient_XMPP_ERROR_SOCK_ERR 10L
#undef com_tuenti_voice_VoiceClient_XMPP_ERROR_STREAM
#define com_tuenti_voice_VoiceClient_XMPP_ERROR_STREAM 2L
#undef com_tuenti_voice_VoiceClient_XMPP_ERROR_TLS
#define com_tuenti_voice_VoiceClient_XMPP_ERROR_TLS 5L
#undef com_tuenti_voice_VoiceClient_XMPP_ERROR_UNAUTH
#define com_tuenti_voice_VoiceClient_XMPP_ERROR_UNAUTH 4L
#undef com_tuenti_voice_VoiceClient_XMPP_ERROR_UNKNOWN
#define com_tuenti_voice_VoiceClient_XMPP_ERROR_UNKNOWN 11L
#undef com_tuenti_voice_VoiceClient_XMPP_ERROR_VERSION
#define com_tuenti_voice_VoiceClient_XMPP_ERROR_VERSION 3L
#undef com_tuenti_voice_VoiceClient_XMPP_ERROR_XML
#define com_tuenti_voice_VoiceClient_XMPP_ERROR_XML 1L
/*
 * Class:     com_tuenti_voice_VoiceClient
 * Method:    nativeAcceptCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tuenti_voice_VoiceClient_nativeAcceptCall
  (JNIEnv *, jobject);

/*
 * Class:     com_tuenti_voice_VoiceClient
 * Method:    nativeCall
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tuenti_voice_VoiceClient_nativeCall
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tuenti_voice_VoiceClient
 * Method:    nativeDeclineCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tuenti_voice_VoiceClient_nativeDeclineCall
  (JNIEnv *, jobject);

/*
 * Class:     com_tuenti_voice_VoiceClient
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tuenti_voice_VoiceClient_nativeDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_tuenti_voice_VoiceClient
 * Method:    nativeEndCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tuenti_voice_VoiceClient_nativeEndCall
  (JNIEnv *, jobject);

/*
 * Class:     com_tuenti_voice_VoiceClient
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tuenti_voice_VoiceClient_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_tuenti_voice_VoiceClient
 * Method:    nativeLogin
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_tuenti_voice_VoiceClient_nativeLogin
  (JNIEnv *, jobject, jstring, jstring, jstring, jboolean);

/*
 * Class:     com_tuenti_voice_VoiceClient
 * Method:    nativeLogout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tuenti_voice_VoiceClient_nativeLogout
  (JNIEnv *, jobject);

/*
 * Class:     com_tuenti_voice_VoiceClient
 * Method:    nativeRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tuenti_voice_VoiceClient_nativeRelease
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
